project/models.py
from datetime import datetime
from flask import current_app
from flask_login import UserMixin
from project import db, bcrypt, login


class User(UserMixin, db.Model):
    __tablename__ = "users"
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    name = db.Column(db.String(128), nullable=False)
    email = db.Column(db.String(128), unique=True, nullable=False)
    password = db.Column(db.String(255), nullable=False)
    exercises = db.relationship("Exercise", backref="author", lazy="dynamic")

    def __init__(self, name, email, password):
        self.name = name
        self.email = email
        self.password = bcrypt.generate_password_hash(
            password, current_app.config.get("BCRYPT_LOG_ROUNDS")
        ).decode()

    def check_password(self, password):
        return bcrypt.check_password_hash(self.password, password)

    @property
    def calories_burnt(self):
        exercises = Exercise.query.filter(Exercise.user_id == self.id).all()
        calories = 0
        for exercise in exercises:
            calories += exercise.calories
        return calories


@login.user_loader
def load_user(id):
    return User.query.get(int(id))


class Exercise(db.Model):
    __tablename__ = "exercises"
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    exercise = db.Column(db.String(64), nullable=False)
    calories = db.Column(db.Integer, nullable=False)
    timestamp = db.Column(db.DateTime, nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"))

    def __init__(self, exercise, calories, timestamp, author):
        self.exercise = exercise
        self.calories = calories
        self.timestamp = timestamp
        self.user_id = author.id

    @property
    def date(self):
        return self.timestamp.date()

    @property
    def author_name(self):
        user = User.query.filter_by(id=self.user_id).first()
        return user.name

project/forms.py
from datetime import datetime
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, IntegerField, DateField
from wtforms.validators import DataRequired, Email, EqualTo, ValidationError
from project.models import User


class LoginForm(FlaskForm):
    email = StringField("Email", validators=[DataRequired(), Email()])
    password = PasswordField("Password", validators=[DataRequired()])
    submit = SubmitField("Sign In")


class ExerciseForm(FlaskForm):
    exercise = StringField("Exercise", validators=[DataRequired()])
    calories = IntegerField("Calories Burnt", validators=[DataRequired()])
    date = DateField(
        "Date", format="%d/%m/%y", default=datetime.today, validators=[DataRequired()]
    )
    submit = SubmitField("Add")

    def validate_date(self, date):
        start = datetime(2019, 10, 1)
        end = datetime(2019, 11, 1)
        given_date = datetime(date.data.year, date.data.month, date.data.day)
        if not start <= given_date < end:
            raise ValidationError("Date must be in October.")


class RegistrationForm(FlaskForm):
    name = StringField("Name", validators=[DataRequired()])
    email = StringField("Email", validators=[DataRequired(), Email()])
    password = PasswordField("Password", validators=[DataRequired()])
    password2 = PasswordField(
        "Repeat Password", validators=[DataRequired(), EqualTo("password")]
    )
    submit = SubmitField("Register")

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        valid_emails = [
            "vilius@email.com",
            "titas@email.com",
            "marius@email.com"
        ]
        if user is not None or email.data not in valid_emails:
            raise ValidationError("Please use a different email address.")

project/main/forms.py
from datetime import datetime
from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField, DateField, SubmitField
from wtforms.validators import DataRequired, ValidationError


class ExerciseForm(FlaskForm):
    exercise = StringField("Exercise", validators=[DataRequired()])
    calories = IntegerField("Calories Burnt", validators=[DataRequired()])
    date = DateField(
        "Date", format="%d/%m/%y", default=datetime.today, validators=[DataRequired()]
    )
    submit = SubmitField("Add")

    def validate_calories(self, calories):
        if not calories.data > 0:
            raise ValidationError(
                "Cannot enter a negative amount of calories."
            )

    def validate_date(self, date):
        start = datetime(2020, 10, 1)
        if datetime.now() < datetime(2020, 11, 1):
            end = datetime.now()
        else:
            end = datetime(2020, 10, 1)
        given_date = datetime(date.data.year, date.data.month, date.data.day)
        if not start <= given_date < end:
            raise ValidationError(
                "Date must be between the 1st of October and today."
            )

project/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_bcrypt import Bcrypt
from flask_login import LoginManager
from flask_bootstrap import Bootstrap

db = SQLAlchemy()
migrate = Migrate()
bcrypt = Bcrypt()
login = LoginManager()
login.login_view = "auth.login"
bootstrap = Bootstrap()


def create_app(config="DevelopmentConfig"):
    app = Flask(__name__)
    app.config.from_object(f"project.config.{config}")

    db.init_app(app)
    migrate.init_app(app, db)
    bcrypt.init_app(app)
    login.init_app(app)
    bootstrap.init_app(app)

    from project.errors.handlers import bp as errors_bp
    app.register_blueprint(errors_bp)

    from project.auth.routes import bp as auth_bp
    app.register_blueprint(auth_bp, url_prefix="/auth")

    from project.main.routes import bp as main_bp
    app.register_blueprint(main_bp)

    return app

project/main/routes.py
from datetime import date, timedelta

from flask import Blueprint, render_template, redirect, url_for, flash
from flask_login import login_required, current_user

from project import db
from project.models import User, Exercise
from project.main.forms import ExerciseForm

bp = Blueprint("main", __name__)


@bp.route("/")
def index():
    return render_template("main/index.html")


@bp.route("/add_exercise", methods=["GET", "POST"])
@login_required
def add_exercise():
    form = ExerciseForm()
    if form.validate_on_submit():

        exercise = Exercise(
            exercise=form.exercise.data,
            calories=form.calories.data,
            timestamp=form.date.data,
            author=current_user
        )
        db.session.add(exercise)
        db.session.commit()

        flash("Great job partner! Make sure to come back tomorrow and GET SOME MORE!")
        return redirect(url_for("main.standings"))

    return render_template("main/add_exercise.html", form=form)


@bp.route("/standings")
@login_required
def standings():
    users = sorted(User.query.all(), key=lambda k: k.calories_burnt, reverse=True)
    standings = []

    for place, user in enumerate(users, start=1):
        standings.append(
            {"place": place, "name": user.name, "calories": user.calories_burnt}
        )

    exercises = sorted(Exercise.query.all(), key=lambda k: k.calories, reverse=True)[:3]
    top_exercises = []

    for place, exercise in enumerate(exercises, start=1):
        top_exercises.append(
            {"place": place,
             "name": User.query.get(exercise.user_id).name,
             "calories": exercise.calories,
             "exercise": exercise.exercise}
        )

    return render_template("main/standings.html", standings=standings,
                           top_exercises=top_exercises)


@bp.route("/history")
@login_required
def history():
    start_date = date(2019, 10, 1)
    delta = date.today() - start_date
    exercises = Exercise.query.all()
    data = []
    for day_index in range(delta.days + 1):
        day = start_date + timedelta(days=day_index)
        todays_exercises = []
        for exercise in exercises:
            if day == exercise.date:
                todays_exercises.append({
                    "author": exercise.author_name,
                    "exercise": exercise.exercise,
                    "calories": exercise.calories
                })
        data.append({
            "date": day,
            "exercises": todays_exercises
        })
    return render_template("main/history.html", data=data)

project/templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}
Sober October
{% endblock %}

{% block navbar %}
<nav class="navbar navbar-default navbar-dark">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                data-target="#bs-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="{{ url_for('main.index') }}" class="navbar-brand">Sober October</a>
        </div>
        <div class="collapse navbar-collapse" id="bs-navbar-collapse-1">
            <ul class="nav navbar-nav">
                {% if not current_user.is_anonymous %}
                <li><a href="{{ url_for('main.add_exercise') }}">Add Exercise</a></li>
                <li><a href="{{ url_for('main.standings') }}">Standings</a></li>
                <li><a href="{{ url_for('main.history') }}">History</a></li>
                {% endif %}
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if current_user.is_anonymous %}
                <li><a href="{{ url_for('auth.login') }}">Login</a></li>
                <li><a href="{{ url_for('auth.registration') }}">Registration</a></li>
                {% else %}
                <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
{% endblock %}

{% block content %}
<div class="container">
    {% with messages = get_flashed_messages() %}
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-info" role="alert">{{ message }}</div>
    {% endfor %}
    {% endif %}
    {% endwith %}

    {% block app_content %}
    {% endblock %}
</div>
{% endblock %}

project/templates/main/add_exercise.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block app_content %}
<div class="page-header">
    <h1>Add Exercise</h1>
</div>

<div class="row">
    <div class="col-md-4">
        {{ wtf.quick_form(form) }}
    </div>
</div>
{% endblock %}

{% block scripts %}
<script src="{{ url_for('static', filename='javascript/button_control.js') }}"></script>
{{ super() }}
{% endblock %}

project/templates/main/history.html
{% extends "base.html" %}

{% block styles %}
{{ super() }}
<link rel="stylesheet" href="{{ url_for('static', filename='styles/history.css') }}">
{% endblock %}

{% block app_content %}
<div class="page-header">
    <h1>History</h1>
</div>
{% for row in data[::-1] %}
{% if row["exercises"] %}
<button class="accordion">{{ row["date"] }}</button>
<div class="panel panel-default">
    {% for exercise in row["exercises"] %}
    <p>{{ exercise["author"] }}: {{ exercise["exercise"] }} for {{ exercise["calories"] }} calories</p>
    {% endfor %}
</div>
{% endif %}
{% endfor %}
{% endblock %}

{% block scripts %}
<script src="{{ url_for('static', filename='javascript/history.js') }}"></script>
{{ super() }}
{% endblock %}

project/templates/main/index.html
{% extends "base.html" %}

{% block app_content %}
<div class="page-header">
    <h1>Sober October Challenge</h1>
</div>

<h4>Saying NO to drugs, alcohol and caffeine.</h4>
<h4>Saying YES to sweat, pain and burnt calories.</h4>
<hr>
<h5>Inspired by Joe Rogan, Ari Shaffir, Tom Segura and Bert Kreischer.</h5>
{% endblock %}

project/templates/main/standings.html
{% extends "base.html" %}

{% block app_content %}
<div class="page-header">
    <h1>Standings</h1>
</div>

<h4>Total Calories</h4>

<div>
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Person</th>
                <th scope="col">Calories</th>
            </tr>
        </thead>
        <tbody>
            {% for user in standings %}
                <tr>
                    <th scope="row">{{ user["place"] }}</th>
                    <td>{{ user["name"] }}</td>
                    <td>{{ user["calories"] }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

<hr>
<h4>Single Exercise</h4>

<div>
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Person</th>
                <th scope="col">Calories</th>
                <th scope="col">Exercise</th>
            </tr>
        </thead>
        <tbody>
            {% for exercise in top_exercises %}
                <tr>
                    <th scope="row">{{ exercise["place"] }}</th>
                    <td>{{ exercise["name"] }}</td>
                    <td>{{ exercise["calories"] }}</td>
                    <td>{{ exercise["exercise"] }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

project/templates/registration.html
{% extends "base.html" %}

{% block content %}
<h1>Register</h1>
<form action="" method="post">
    {{ form.hidden_tag() }}
    <p>
        {{ form.name.label }}<br>
        {{ form.name(size=32) }}<br>
        {% for error in form.name.errors %}
        <span style="color: red;">[{{ error }}]</span>
        {% endfor %}
    </p>
    <p>
        {{ form.email.label }}<br>
        {{ form.email(size=32) }}<br>
        {% for error in form.email.errors %}
        <span style="color: red;">[{{ error }}]</span>
        {% endfor %}
    </p>
    <p>
        {{ form.password.label }}<br>
        {{ form.password(size=32) }}<br>
        {% for error in form.password.errors %}
        <span style="color: red;">[{{ error }}]</span>
        {% endfor %}
    </p>
    <p>
        {{ form.password2.label }}<br>
        {{ form.password2(size=32) }}<br>
        {% for error in form.password2.errors %}
        <span style="color: red;">[{{ error }}]</span>
        {% endfor %}
    </p>
    <p>
        {{ form.submit() }}
    </p>
</form>
{% endblock %}